[package]
name = "load_balancer"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
pingora-core = "0.6"
pingora = {version = "0.6", features = ["lb"]}
sfv = { version = "0.14.0", default-features = false }
